In [1]:
import pandas as pd
import numpy as np

In [2]:
crop=pd.read_csv('crop_price.csv')

In [3]:
crop.head()

APMC      Commodity  Year  Month  arrivals_in_qtl  min_price  \
0  Ahmednagar          Bajri  2015  April               79       1406   
1  Ahmednagar          Bajri  2016  April              106       1788   
2  Ahmednagar  Wheat(Husked)  2015  April             1253       1572   
3  Ahmednagar  Wheat(Husked)  2016  April              387       1750   
4  Ahmednagar  Sorgum(Jawar)  2015  April             3825       1600   

   max_price  modal_price     date district_name   state_name  
0       1538         1463  2015-04    Ahmadnagar  Maharashtra  
1       1925         1875  2016-04    Ahmadnagar  Maharashtra  
2       1890         1731  2015-04    Ahmadnagar  Maharashtra  
3       2220         1999  2016-04    Ahmadnagar  Maharashtra  
4       2200         1900  2015-04    Ahmadnagar  Maharashtra

In [4]:
crop.shape

(62429, 11)

In [5]:
crop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62429 entries, 0 to 62428
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   APMC             62429 non-null  object
 1   Commodity        62429 non-null  object
 2   Year             62429 non-null  int64 
 3   Month            62429 non-null  object
 4   arrivals_in_qtl  62429 non-null  int64 
 5   min_price        62429 non-null  int64 
 6   max_price        62429 non-null  int64 
 7   modal_price      62429 non-null  int64 
 8   date             62429 non-null  object
 9   district_name    62429 non-null  object
 10  state_name       62429 non-null  object
dtypes: int64(5), object(6)
memory usage: 5.2+ MB


In [6]:
crop['APMC'].unique()


array(['Ahmednagar', 'Akole', 'Jamkhed', 'Kopargaon', 'Newasa',
       'Newasa-Ghodegaon', 'Parner', 'Pathardi', 'Rahata', 'Rahuri',
       'Rahuri-Vambori', 'Sangamner', 'Shevgaon', 'Shevgaon-Bodhegaon',
       'Shrirampur', 'Shrirampur-Belapur', 'Shrigonda',
       'Shrigonda-Ghogargaon', 'Karjat (A- Nagar)', 'Rahuri-Songaon',
       'Akola', 'Akot', 'Balapur', 'Murtizapur', 'Patur', 'Telhara',
       'Barshi Takli', 'Achalpur', 'Amarawati',
       'Amarawati-Fruit And Vegetables', 'Anajngaon Surji',
       'Chandur Bajar', 'Chandur Rly.', 'Daryapur', 'Dhamangaon-Rly',
       'Dharni', 'Morshi', 'Nandgaon Khandeshwar', 'Varud',
       'Varud-Rajura Bazar', 'Tiwasa', 'Aurangabad', 'Fulambri',
       'Gangapur', 'Kannad', 'Lasur Station', 'Paithan', 'Sillod',
       'Sillod-Bharadi', 'Soygaon', 'Vaijapur', 'Khultabad', 'Ambejogai',
       'Beed', 'Gevrai', 'Kada', 'Kada (Ashti)', 'Kej', 'Kille Dharur',
       'Majalgaon', 'Parli-Vaijnath', 'Bhandara', 'Lakhandur', 'Lakhani',
       'Pa

In [7]:
crop['Commodity'].unique()

array(['Bajri', 'Wheat(Husked)', 'Sorgum(Jawar)', 'Maize', 'Gram',
       'Horse Gram', 'Matki', 'Pigeon Pea (Tur)', 'Black Gram',
       'Castor Seed', 'Soybean', 'Jaggery', 'Lemon', 'Ginger (Fresh)',
       'Potato', 'Ladies Finger', 'Flower', 'Carrot', 'Cluster Bean',
       'Ghevda', 'Ghosali(Bhaji)', 'Mango(Raw)', 'Cucumber', 'Onion',
       'Bitter Gourd', 'Cabbage', 'Garlic', 'Math (Bhaji)', 'Capsicum',
       'Tomato', 'Brinjal', 'Tamarind', 'Tamarind Seed',
       'Coriander (Dry)', 'Green Chilli', 'Chillies(Red)', 'Mustard',
       'Paddy-Unhusked', 'Hilda', 'Chikoo', 'Cotton',
       'Ground Nut Pods (Dry)', 'Pomegranate', 'Papai', 'Melon',
       'Beet Root', 'Bottle Gourd', 'Dhemse', 'Coriander ', 'Coriander  ',
       'Spinach', 'Shevga', 'Small Gourd', 'Grapes', 'Kharbuj',
       'Green Gram', 'Sunflower', 'Safflower', 'Mango', 'Water Melon',
       'Mosambi', 'Orange', 'Fenugreek', 'Cowpea', 'Green Peas (Dry)',
       'Squash Gourd', 'Maize (Corn.)', 'Chino', 'Curry Lea

In [8]:
crop['Year'].unique() ### year should be in integer not in objects

array([2015, 2016, 2014], dtype=int64)

In [9]:
crop['arrivals_in_qtl'].unique()

array([    79,    106,   1253, ...,  60582, 101385,  15490], dtype=int64)

In [10]:
crop['Month'].unique()

array(['April', 'August', 'December', 'February', 'January', 'July',
       'June', 'March', 'May', 'November', 'October', 'September'],
      dtype=object)

In [11]:
crop['modal_price'].unique()

array([  1463,   1875,   1731, ...,  24131, 142344,   6761], dtype=int64)

In [12]:
crop['district_name'].unique()

array(['Ahmadnagar', 'Akola', 'Amaravathi', 'Aurangabad', 'Beed',
       'Bhandara', 'Buldhana', 'Chandrapur', 'Dhule', 'Gadchiroli',
       'Gondiya', 'Hingoli', 'Jalgaon', 'Jalna', 'Kolhapur', 'Latur',
       'Mumbai', 'Nagpur', 'Nanded', 'Nandurbar', 'Nasik', 'Osmanabad',
       'Parbhani', 'Pune', 'Raigad', 'Ratnagiri', 'Sangli', 'Satara',
       'Solapur', 'Thane', 'Wardha', 'Wasim', 'Yewatmal'], dtype=object)

In [13]:
crop['date'].unique()

array(['2015-04', '2016-04', '2015-08', '2016-08', '2015-12', '2014-12',
       '2015-02', '2016-02', '2015-01', '2016-01', '2015-07', '2016-07',
       '2015-06', '2016-06', '2015-03', '2016-03', '2016-05', '2015-05',
       '2014-11', '2015-11', '2015-10', '2016-10', '2014-10', '2014-09',
       '2015-09', '2016-09', '2016-11'], dtype=object)

In [14]:
backup=crop.copy()

In [15]:
crop=crop.drop(columns="state_name")

In [16]:
crop.head()

APMC      Commodity  Year  Month  arrivals_in_qtl  min_price  \
0  Ahmednagar          Bajri  2015  April               79       1406   
1  Ahmednagar          Bajri  2016  April              106       1788   
2  Ahmednagar  Wheat(Husked)  2015  April             1253       1572   
3  Ahmednagar  Wheat(Husked)  2016  April              387       1750   
4  Ahmednagar  Sorgum(Jawar)  2015  April             3825       1600   

   max_price  modal_price     date district_name  
0       1538         1463  2015-04    Ahmadnagar  
1       1925         1875  2016-04    Ahmadnagar  
2       1890         1731  2015-04    Ahmadnagar  
3       2220         1999  2016-04    Ahmadnagar  
4       2200         1900  2015-04    Ahmadnagar

In [17]:
crop=crop.drop(columns="date")

In [18]:
crop.head()

APMC      Commodity  Year  Month  arrivals_in_qtl  min_price  \
0  Ahmednagar          Bajri  2015  April               79       1406   
1  Ahmednagar          Bajri  2016  April              106       1788   
2  Ahmednagar  Wheat(Husked)  2015  April             1253       1572   
3  Ahmednagar  Wheat(Husked)  2016  April              387       1750   
4  Ahmednagar  Sorgum(Jawar)  2015  April             3825       1600   

   max_price  modal_price district_name  
0       1538         1463    Ahmadnagar  
1       1925         1875    Ahmadnagar  
2       1890         1731    Ahmadnagar  
3       2220         1999    Ahmadnagar  
4       2200         1900    Ahmadnagar

In [19]:
crop=crop.drop(columns="min_price")

In [20]:
crop=crop.drop(columns="max_price")

In [21]:
crop.head()

APMC      Commodity  Year  Month  arrivals_in_qtl  modal_price  \
0  Ahmednagar          Bajri  2015  April               79         1463   
1  Ahmednagar          Bajri  2016  April              106         1875   
2  Ahmednagar  Wheat(Husked)  2015  April             1253         1731   
3  Ahmednagar  Wheat(Husked)  2016  April              387         1999   
4  Ahmednagar  Sorgum(Jawar)  2015  April             3825         1900   

  district_name  
0    Ahmadnagar  
1    Ahmadnagar  
2    Ahmadnagar  
3    Ahmadnagar  
4    Ahmadnagar

In [22]:
crop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62429 entries, 0 to 62428
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   APMC             62429 non-null  object
 1   Commodity        62429 non-null  object
 2   Year             62429 non-null  int64 
 3   Month            62429 non-null  object
 4   arrivals_in_qtl  62429 non-null  int64 
 5   modal_price      62429 non-null  int64 
 6   district_name    62429 non-null  object
dtypes: int64(3), object(4)
memory usage: 3.3+ MB


In [23]:
crop

APMC      Commodity  Year     Month  arrivals_in_qtl  \
0      Ahmednagar          Bajri  2015     April               79   
1      Ahmednagar          Bajri  2016     April              106   
2      Ahmednagar  Wheat(Husked)  2015     April             1253   
3      Ahmednagar  Wheat(Husked)  2016     April              387   
4      Ahmednagar  Sorgum(Jawar)  2015     April             3825   
...           ...            ...   ...       ...              ...   
62424   Shrigonda           GRAM  2016  November              586   
62425   Shrigonda     GREEN GRAM  2016  November                2   
62426   Shrigonda     BLACK GRAM  2016  November               46   
62427   Shrigonda        SOYBEAN  2016  November              166   
62428   Shrigonda      SUNFLOWER  2016  November               74   

       modal_price district_name  
0             1463    Ahmadnagar  
1             1875    Ahmadnagar  
2             1731    Ahmadnagar  
3             1999    Ahmadnagar  
4             1900    Ahmadnagar  
...            ...           ...  
62424         6200    Ahmadnagar  
62425         5000    Ahmadnagar  
62426         6400    Ahmadnagar  
62427         2633    Ahmadnagar  
62428         3067    Ahmadnagar  

[62429 rows x 7 columns]

In [24]:
#MODEL



In [25]:
crop.describe()

Year  arrivals_in_qtl    modal_price
count  62429.000000     6.242900e+04   62429.000000
mean    2015.337503     6.043088e+03    3296.003989
std        0.690451     3.470331e+04    3607.792534
min     2014.000000     1.000000e+00       0.000000
25%     2015.000000     3.800000e+01    1450.000000
50%     2015.000000     2.110000e+02    2425.000000
75%     2016.000000     1.364000e+03    4257.000000
max     2016.000000     1.450254e+06  142344.000000

In [26]:
crop.to_csv('Cleaned crop.csv')
crop.head()

APMC      Commodity  Year  Month  arrivals_in_qtl  modal_price  \
0  Ahmednagar          Bajri  2015  April               79         1463   
1  Ahmednagar          Bajri  2016  April              106         1875   
2  Ahmednagar  Wheat(Husked)  2015  April             1253         1731   
3  Ahmednagar  Wheat(Husked)  2016  April              387         1999   
4  Ahmednagar  Sorgum(Jawar)  2015  April             3825         1900   

  district_name  
0    Ahmadnagar  
1    Ahmadnagar  
2    Ahmadnagar  
3    Ahmadnagar  
4    Ahmadnagar

In [27]:
x=crop.drop(columns='modal_price')
y=crop['modal_price']

In [28]:
x

APMC      Commodity  Year     Month  arrivals_in_qtl  \
0      Ahmednagar          Bajri  2015     April               79   
1      Ahmednagar          Bajri  2016     April              106   
2      Ahmednagar  Wheat(Husked)  2015     April             1253   
3      Ahmednagar  Wheat(Husked)  2016     April              387   
4      Ahmednagar  Sorgum(Jawar)  2015     April             3825   
...           ...            ...   ...       ...              ...   
62424   Shrigonda           GRAM  2016  November              586   
62425   Shrigonda     GREEN GRAM  2016  November                2   
62426   Shrigonda     BLACK GRAM  2016  November               46   
62427   Shrigonda        SOYBEAN  2016  November              166   
62428   Shrigonda      SUNFLOWER  2016  November               74   

      district_name  
0        Ahmadnagar  
1        Ahmadnagar  
2        Ahmadnagar  
3        Ahmadnagar  
4        Ahmadnagar  
...             ...  
62424    Ahmadnagar  
62425    Ahmadnagar  
62426    Ahmadnagar  
62427    Ahmadnagar  
62428    Ahmadnagar  

[62429 rows x 6 columns]

In [29]:
y

0        1463
1        1875
2        1731
3        1999
4        1900
         ... 
62424    6200
62425    5000
62426    6400
62427    2633
62428    3067
Name: modal_price, Length: 62429, dtype: int64

In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [31]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [32]:
ohe=OneHotEncoder()
ohe.fit(x[['APMC','Commodity','Month','district_name']])


OneHotEncoder()

In [33]:
# pass all these categories to one hot encoding
ohe.categories_

[array(['Aamgaon', 'Aarni', 'Achalpur', 'Aheri', 'Ahmednagar', 'Ahmedpur',
        'Akhadabalapur', 'Akkalkuwa', 'Akkolkot', 'Akluj', 'Akola',
        'Akole', 'Akot', 'Alibag', 'Amalner', 'Amarawati',
        'Amarawati-Fruit And Vegetables', 'Ambad(Vadi Godri)', 'Ambejogai',
        'Anajngaon Surji', 'Arjuni Morgaon', 'Armori', 'Armori-Desaiganj',
        'Arvi', 'Ashti (Jalna)', 'Ashti (Wardha)', 'Ashti-Karanja',
        'Atpadi', 'Aurad Shahajani', 'Aurangabad', 'Ausa', 'Babhulgaon',
        'Balapur', 'Baramati', 'Barshi', 'Barshi Takli', 'Barshi-Vairag',
        'Basmat', 'Basmat (Kurunda)', 'Beed', 'Bhadrawati', 'Bhandara',
        'Bhivandi', 'Bhiwapur', 'Bhokar', 'Bhokardan',
        'Bhokardan-Pimpalgaon Renu', 'Bhoom', 'Bhor', 'Bhusaval', 'Biloli',
        'Bodwad-Varangaon', 'Bori', 'Bori Arab', 'Brahmpuri', 'Buldhana',
        'Buldhana-Dhad', 'Chakur', 'Chalisgaon', 'Chamorshi', 'Chandrapur',
        'Chandrapur-Ganjwad', 'Chandur Bajar', 'Chandur Rly.', 'Chandvad',
    

In [34]:
## column transform tells that just perform oneHotEncoding to categories and pass the rest column
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_),['APMC','Commodity','Month','district_name']),remainder='passthrough')

In [35]:
lr=LinearRegression()

In [36]:
pipe=make_pipeline(column_trans,lr)## make pipeline of columnn_transform and linear regression

In [37]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Aamgaon', 'Aarni', 'Achalpur', 'Aheri', 'Ahmednagar', 'Ahmedpur',
       'Akhadabalapur', 'Akkalkuwa', 'Akkolkot', 'Akluj', 'Akola',
       'Akole', 'Akot', 'Alibag', 'Amalner', 'Amarawati',
       'Amarawati-Fruit And Vegetables', 'Ambad(Vadi God...
       'Bhandara', 'Buldhana', 'Chandrapur', 'Dhule', 'Gadchiroli',
       'Gondiya', 'Hingoli', 'Jalgaon', 'Jalna', 'Kolhapur', 'Latur',
       'Mumbai', 'Nagpur', 'Nanded', 'Nandurbar', 'Nasik', 'Osmanabad',
       'Parbhani', 'Pune', 'Raigad', 'Ratnagiri', 'Sangli', 'Satara',
       'Solapur', 'Thane', 'Wardha', 'Wasim', 'Yewatmal'], dtype=object)]),
                                                  ['APMC', 'Commodity', 'Month',
                                                   'district_na

In [38]:
y_pred=pipe.predict(x_test)
y_pred

array([3538.51860451, 1319.80838108, 1790.93866129, ..., 1975.93927737,
       7062.15926899, 1052.47663613])

In [39]:
r2_score(y_test,y_pred)

0.7916436448138863

In [40]:
## to find the best score we are spliting 10 times 
scores=[]
for i in range(10):
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(x_train,y_train)
    y_pred=pipe.predict(x_test)
    scores.append(r2_score(y_test,y_pred))

In [41]:
np.argmax(scores)

9

In [42]:
scores[np.argmax(scores)]

0.8611617743475541

In [43]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=np.argmax(scores))
lr=LinearRegression()
pipe=make_pipeline(column_trans,lr)
pipe.fit(x_train,y_train)
y_pred=pipe.predict(x_test)
scores.append(r2_score(y_test,y_pred))
r2_score(y_test,y_pred)

0.8611617743475541

In [44]:
 import pickle

In [45]:
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))


In [46]:
pipe.predict(pd.DataFrame([['Ahmednagar','Sorgum(Jawar)','2022','November',821,'Ahmadnagar']],columns=['APMC','Commodity','Year','Month','arrivals_in_qtl','district_name']))

array([4794.07458116])

In [54]:

# Loading model to compare the results
model = pickle.load(open('LinearRegressionModel.pkl','rb'))
pred=model.predict(pd.DataFrame([['Ahmednagar', 'Bajri', 2024, 'April',100,'Ahmadnagar']],columns=['APMC','Commodity','Year','Month','arrivals_in_qtl','district_name']))
print(pred)

[5074.97308158]
